version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose port 80 for the web app
    container_name: artful-route-mapper
    restart: unless-stopped
    environment:
      - NODE_ENV=production